import Link from "next/link";
import { ArrowRight, BookOpen, BrainCircuit, ContactRound, Plus, UserRoundPlus } from "lucide-react";
import { getDashboardData } from "../../db/repository";
import { StatusBadge } from "../components/AdminUI";

export default async function AdminDashboard() {
  const data = await getDashboardData();
  const cards = [{ label: "Leads nuevos", value: data.counts.newContacts, icon: UserRoundPlus, tone: "blue" }, { label: "Total contactos", value: data.counts.contacts, icon: ContactRound, tone: "navy" }, { label: "Entrenamientos publicados", value: data.counts.trainings, icon: BrainCircuit, tone: "cyan" }, { label: "Artículos publicados", value: data.counts.posts, icon: BookOpen, tone: "violet" }];
  return <><div className="admin-page-heading"><div><span>Vista general</span><h1>Dashboard</h1><p>Actividad y contenidos de Gimnasio del Cerebro en un solo lugar.</p></div><Link className="button button--primary" href="/admin/crm"><Plus size={17} />Añadir contacto</Link></div><div className="dashboard-cards">{cards.map(({ label, value, icon: Icon, tone }) => <div className={`metric-card metric-card--${tone}`} key={label}><span><Icon /></span><div><strong>{value}</strong><p>{label}</p></div></div>)}</div><div className="dashboard-grid"><section className="admin-card admin-card--wide"><div className="admin-card__heading"><div><h2>Leads recientes</h2><p>Consultas recibidas desde el sitio.</p></div><Link href="/admin/crm">Ver CRM <ArrowRight size={16} /></Link></div>{data.recent.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Persona</th><th>Interés</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{data.recent.map((contact) => <tr key={contact.id}><td><strong>{contact.name}</strong><span>{contact.email}</span></td><td>{contact.trainingInterest || "Por definir"}</td><td><StatusBadge status={contact.status} /></td><td>{new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short" }).format(new Date(contact.createdAt))}</td></tr>)}</tbody></table></div> : <div className="admin-empty"><ContactRound /><h3>Todavía no hay contactos.</h3><p>Los nuevos formularios aparecerán aquí automáticamente.</p></div>}</section><aside className="admin-card"><div className="admin-card__heading"><div><h2>Acciones rápidas</h2><p>Atajos frecuentes.</p></div></div><div className="quick-actions"><Link href="/admin/blog"><BookOpen /><span><strong>Crear artículo</strong>Publica una nueva lectura.</span><ArrowRight /></Link><Link href="/admin/entrenamientos"><BrainCircuit /><span><strong>Gestionar entrenamientos</strong>Edita el catálogo actual.</span><ArrowRight /></Link><Link href="/admin/crm"><ContactRound /><span><strong>Revisar contactos</strong>Organiza el seguimiento.</span><ArrowRight /></Link></div></aside></div></>;
}
