"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Edit3, Plus, Search, UploadCloud } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { BlogPost, Contact, Training } from "../../db/repository";

const statusLabels: Record<string, string> = { NEW: "Nuevo", CONTACTED: "Contactado", INTERESTED: "Interesado", FOLLOW_UP: "Seguimiento", ENROLLED: "Inscrito", NOT_INTERESTED: "No interesado", CLOSED: "Cerrado", DRAFT: "Borrador", PUBLISHED: "Publicado", HIDDEN: "Oculto", ARCHIVED: "Archivado" };
export function StatusBadge({ status }: { status: string }) { return <span className={`status-badge status-badge--${status.toLowerCase()}`}>{statusLabels[status] ?? status}</span>; }

export function CrmTable({ contacts }: { contacts: Contact[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("");
  const filtered = useMemo(() => contacts.filter((contact) => `${contact.name} ${contact.email} ${contact.phone}`.toLowerCase().includes(query.toLowerCase()) && (!status || contact.status === status)), [contacts, query, status]);
  return <><div className="admin-toolbar"><label><Search size={17} /><input placeholder="Buscar por nombre, email o teléfono" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos los estados</option>{["NEW", "CONTACTED", "INTERESTED", "FOLLOW_UP", "ENROLLED", "NOT_INTERESTED", "CLOSED"].map((item) => <option value={item} key={item}>{statusLabels[item]}</option>)}</select></div>{filtered.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Persona</th><th>Contacto</th><th>Interés</th><th>Estado</th><th>Fuente</th><th>Fecha</th><th /></tr></thead><tbody>{filtered.map((contact) => <tr key={contact.id}><td><strong>{contact.name}</strong><span>{contact.country}</span></td><td><a href={`mailto:${contact.email}`}>{contact.email}</a><span>{contact.phone}</span></td><td>{contact.trainingInterest || "Por definir"}</td><td><StatusBadge status={contact.status} /></td><td>{contact.source === "website_contact" ? "Formulario web" : contact.source}</td><td>{new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(contact.createdAt))}</td><td><Link className="icon-action" href={`/admin/crm/${contact.id}`} aria-label={`Abrir contacto ${contact.name}`}><ArrowRight size={17} /></Link></td></tr>)}</tbody></table></div> : <div className="admin-empty"><Search /><h3>Todavía no hay contactos con estos filtros.</h3><p>Los nuevos formularios aparecerán aquí automáticamente.</p></div>}</>;
}

export function ContactEditor({ contact }: { contact: Contact }) {
  const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/admin/contacts/${contact.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); setLoading(false); setSaved(response.ok); }
  return <form className="contact-editor" onSubmit={submit}><label>Estado<select name="status" defaultValue={contact.status}>{["NEW", "CONTACTED", "INTERESTED", "FOLLOW_UP", "ENROLLED", "NOT_INTERESTED", "CLOSED"].map((item) => <option value={item} key={item}>{statusLabels[item]}</option>)}</select></label><label>Próximo seguimiento<input type="date" name="nextFollowUp" defaultValue={contact.nextFollowUp?.slice(0, 10) ?? ""} /></label><label>Agregar nota<textarea name="note" rows={4} placeholder="Escribe una nota interna…" /></label><button className="button button--primary" disabled={loading}>{loading ? "Guardando…" : "Guardar cambios"}</button>{saved && <p className="inline-success"><Check size={16} />Cambios guardados</p>}</form>;
}

export function ContentManager({ kind, trainings = [], posts = [] }: { kind: "trainings" | "posts"; trainings?: Training[]; posts?: BlogPost[] }) {
  const [creating, setCreating] = useState(false); const [notice, setNotice] = useState(""); const items = kind === "trainings" ? trainings.map((item) => ({ id: item.id, title: item.name, meta: item.acronym, status: item.status, image: item.logo })) : posts.map((item) => ({ id: item.id, title: item.title, meta: item.category, status: item.status, image: "" }));
  async function changeStatus(id: string, status: string) { const response = await fetch(`/api/admin/${kind}/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); setNotice(response.ok ? "Estado actualizado correctamente." : "No se pudo actualizar."); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const response = await fetch(`/api/admin/${kind}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); if (response.ok) { setNotice("Registro creado como borrador."); form.reset(); setCreating(false); window.location.reload(); } else setNotice("Revisa los datos ingresados."); }
  return <><div className="manager-actions"><button className="button button--primary" type="button" onClick={() => setCreating((value) => !value)}><Plus size={17} />{kind === "trainings" ? "Nuevo entrenamiento" : "Nuevo artículo"}</button>{notice && <span>{notice}</span>}</div>{creating && <form className="manager-form" onSubmit={create}><div className="field-row"><label>{kind === "trainings" ? "Nombre" : "Título"}<input name={kind === "trainings" ? "name" : "title"} required /></label><label>{kind === "trainings" ? "Acrónimo" : "Categoría"}<input name={kind === "trainings" ? "acronym" : "category"} required /></label></div><label>Slug<input name="slug" pattern="[a-z0-9-]+" required /></label><label>{kind === "trainings" ? "Descripción corta" : "Extracto"}<textarea name={kind === "trainings" ? "shortDescription" : "excerpt"} rows={3} required /></label>{kind === "posts" && <label>Contenido<textarea name="content" rows={7} required /></label>}<div className="button-row"><button className="button button--primary">Guardar borrador</button><button className="button button--outline" type="button" onClick={() => setCreating(false)}>Cancelar</button></div></form>}<div className="admin-table-wrap"><table className="admin-table content-table"><thead><tr><th>Contenido</th><th>Identificador</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="content-cell">{item.image ? <Image src={item.image} alt="" width={54} height={54} /> : <span className="content-placeholder"><Edit3 /></span>}<strong>{item.title}</strong></div></td><td>{item.meta}</td><td><select defaultValue={item.status} onChange={(event) => changeStatus(item.id, event.target.value)}>{(kind === "trainings" ? ["DRAFT", "PUBLISHED", "HIDDEN"] : ["DRAFT", "PUBLISHED", "ARCHIVED"]).map((status) => <option value={status} key={status}>{statusLabels[status]}</option>)}</select></td><td><button className="icon-action" type="button" aria-label="Editar"><Edit3 size={17} /></button></td></tr>)}</tbody></table></div></>;
}

export function MediaUpload() {
  const [message, setMessage] = useState(""); async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/media", { method: "POST", body: new FormData(event.currentTarget) }); const payload = await response.json() as { error?: string; name?: string }; setMessage(response.ok ? `${payload.name} se subió correctamente.` : payload.error ?? "No se pudo subir el archivo."); }
  return <form className="media-upload" onSubmit={upload}><UploadCloud /><h3>Subir recurso visual</h3><p>PNG, JPEG, WebP o AVIF. Máximo 8 MB.</p><input type="file" name="file" accept="image/png,image/jpeg,image/webp,image/avif" required /><button className="button button--primary">Subir archivo</button>{message && <span>{message}</span>}</form>;
}
